#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastahane.Modal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Posterolateral")]
	public partial class PosterolateralDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTblTakip(TblTakip instance);
    partial void UpdateTblTakip(TblTakip instance);
    partial void DeleteTblTakip(TblTakip instance);
    partial void InsertTbkPeropErKomp(TbkPeropErKomp instance);
    partial void UpdateTbkPeropErKomp(TbkPeropErKomp instance);
    partial void DeleteTbkPeropErKomp(TbkPeropErKomp instance);
    partial void InsertTbl_PatalojikVeri(Tbl_PatalojikVeri instance);
    partial void UpdateTbl_PatalojikVeri(Tbl_PatalojikVeri instance);
    partial void DeleteTbl_PatalojikVeri(Tbl_PatalojikVeri instance);
    partial void InsertTblAltGrup(TblAltGrup instance);
    partial void UpdateTblAltGrup(TblAltGrup instance);
    partial void DeleteTblAltGrup(TblAltGrup instance);
    partial void InsertTblDemograf(TblDemograf instance);
    partial void UpdateTblDemograf(TblDemograf instance);
    partial void DeleteTblDemograf(TblDemograf instance);
    partial void InsertTblDoktor(TblDoktor instance);
    partial void UpdateTblDoktor(TblDoktor instance);
    partial void DeleteTblDoktor(TblDoktor instance);
    partial void InsertTblFuhrmanGrade(TblFuhrmanGrade instance);
    partial void UpdateTblFuhrmanGrade(TblFuhrmanGrade instance);
    partial void DeleteTblFuhrmanGrade(TblFuhrmanGrade instance);
    partial void InsertTblHasta(TblHasta instance);
    partial void UpdateTblHasta(TblHasta instance);
    partial void DeleteTblHasta(TblHasta instance);
    partial void InsertTblKomorbidite(TblKomorbidite instance);
    partial void UpdateTblKomorbidite(TblKomorbidite instance);
    partial void DeleteTblKomorbidite(TblKomorbidite instance);
    partial void InsertTblKompClavien(TblKompClavien instance);
    partial void UpdateTblKompClavien(TblKompClavien instance);
    partial void DeleteTblKompClavien(TblKompClavien instance);
    partial void InserttblLokalizasyon(tblLokalizasyon instance);
    partial void UpdatetblLokalizasyon(tblLokalizasyon instance);
    partial void DeletetblLokalizasyon(tblLokalizasyon instance);
    partial void InsertTblOperaf(TblOperaf instance);
    partial void UpdateTblOperaf(TblOperaf instance);
    partial void DeleteTblOperaf(TblOperaf instance);
    partial void InsertTblOpTuru(TblOpTuru instance);
    partial void UpdateTblOpTuru(TblOpTuru instance);
    partial void DeleteTblOpTuru(TblOpTuru instance);
    partial void InsertTblPatEvre(TblPatEvre instance);
    partial void UpdateTblPatEvre(TblPatEvre instance);
    partial void DeleteTblPatEvre(TblPatEvre instance);
    partial void InsertTblPatoloji(TblPatoloji instance);
    partial void UpdateTblPatoloji(TblPatoloji instance);
    partial void DeleteTblPatoloji(TblPatoloji instance);
    partial void InsertTblPosOperaf(TblPosOperaf instance);
    partial void UpdateTblPosOperaf(TblPosOperaf instance);
    partial void DeleteTblPosOperaf(TblPosOperaf instance);
    #endregion
		
		public PosterolateralDbDataContext() : 
				base(global::Hastahane.Properties.Settings.Default.PosterolateralConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PosterolateralDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PosterolateralDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PosterolateralDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PosterolateralDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TblTakip> TblTakips
		{
			get
			{
				return this.GetTable<TblTakip>();
			}
		}
		
		public System.Data.Linq.Table<TbkPeropErKomp> TbkPeropErKomps
		{
			get
			{
				return this.GetTable<TbkPeropErKomp>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_PatalojikVeri> Tbl_PatalojikVeris
		{
			get
			{
				return this.GetTable<Tbl_PatalojikVeri>();
			}
		}
		
		public System.Data.Linq.Table<TblAltGrup> TblAltGrups
		{
			get
			{
				return this.GetTable<TblAltGrup>();
			}
		}
		
		public System.Data.Linq.Table<TblDemograf> TblDemografs
		{
			get
			{
				return this.GetTable<TblDemograf>();
			}
		}
		
		public System.Data.Linq.Table<TblDoktor> TblDoktors
		{
			get
			{
				return this.GetTable<TblDoktor>();
			}
		}
		
		public System.Data.Linq.Table<TblFuhrmanGrade> TblFuhrmanGrades
		{
			get
			{
				return this.GetTable<TblFuhrmanGrade>();
			}
		}
		
		public System.Data.Linq.Table<TblHasta> TblHastas
		{
			get
			{
				return this.GetTable<TblHasta>();
			}
		}
		
		public System.Data.Linq.Table<TblKomorbidite> TblKomorbidites
		{
			get
			{
				return this.GetTable<TblKomorbidite>();
			}
		}
		
		public System.Data.Linq.Table<TblKompClavien> TblKompClaviens
		{
			get
			{
				return this.GetTable<TblKompClavien>();
			}
		}
		
		public System.Data.Linq.Table<tblLokalizasyon> tblLokalizasyons
		{
			get
			{
				return this.GetTable<tblLokalizasyon>();
			}
		}
		
		public System.Data.Linq.Table<TblOperaf> TblOperafs
		{
			get
			{
				return this.GetTable<TblOperaf>();
			}
		}
		
		public System.Data.Linq.Table<TblOpTuru> TblOpTurus
		{
			get
			{
				return this.GetTable<TblOpTuru>();
			}
		}
		
		public System.Data.Linq.Table<TblPatEvre> TblPatEvres
		{
			get
			{
				return this.GetTable<TblPatEvre>();
			}
		}
		
		public System.Data.Linq.Table<TblPatoloji> TblPatolojis
		{
			get
			{
				return this.GetTable<TblPatoloji>();
			}
		}
		
		public System.Data.Linq.Table<TblPosOperaf> TblPosOperafs
		{
			get
			{
				return this.GetTable<TblPosOperaf>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblTakip")]
	public partial class TblTakip : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _HastaId;
		
		private string _Postop3Lkl;
		
		private System.Nullable<decimal> _Postop3Krtn;
		
		private string _Postop6Lkl;
		
		private System.Nullable<decimal> _Postop6Krtn;
		
		private string _Postop12Lkl;
		
		private System.Nullable<decimal> _Postop12Krtn;
		
		private EntityRef<TblHasta> _TblHasta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHastaIdChanging(System.Nullable<int> value);
    partial void OnHastaIdChanged();
    partial void OnPostop3LklChanging(string value);
    partial void OnPostop3LklChanged();
    partial void OnPostop3KrtnChanging(System.Nullable<decimal> value);
    partial void OnPostop3KrtnChanged();
    partial void OnPostop6LklChanging(string value);
    partial void OnPostop6LklChanged();
    partial void OnPostop6KrtnChanging(System.Nullable<decimal> value);
    partial void OnPostop6KrtnChanged();
    partial void OnPostop12LklChanging(string value);
    partial void OnPostop12LklChanged();
    partial void OnPostop12KrtnChanging(System.Nullable<decimal> value);
    partial void OnPostop12KrtnChanged();
    #endregion
		
		public TblTakip()
		{
			this._TblHasta = default(EntityRef<TblHasta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaId", DbType="Int")]
		public System.Nullable<int> HastaId
		{
			get
			{
				return this._HastaId;
			}
			set
			{
				if ((this._HastaId != value))
				{
					if (this._TblHasta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIdChanging(value);
					this.SendPropertyChanging();
					this._HastaId = value;
					this.SendPropertyChanged("HastaId");
					this.OnHastaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop3Lkl", DbType="NVarChar(5)")]
		public string Postop3Lkl
		{
			get
			{
				return this._Postop3Lkl;
			}
			set
			{
				if ((this._Postop3Lkl != value))
				{
					this.OnPostop3LklChanging(value);
					this.SendPropertyChanging();
					this._Postop3Lkl = value;
					this.SendPropertyChanged("Postop3Lkl");
					this.OnPostop3LklChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop3Krtn", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> Postop3Krtn
		{
			get
			{
				return this._Postop3Krtn;
			}
			set
			{
				if ((this._Postop3Krtn != value))
				{
					this.OnPostop3KrtnChanging(value);
					this.SendPropertyChanging();
					this._Postop3Krtn = value;
					this.SendPropertyChanged("Postop3Krtn");
					this.OnPostop3KrtnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop6Lkl", DbType="NVarChar(5)")]
		public string Postop6Lkl
		{
			get
			{
				return this._Postop6Lkl;
			}
			set
			{
				if ((this._Postop6Lkl != value))
				{
					this.OnPostop6LklChanging(value);
					this.SendPropertyChanging();
					this._Postop6Lkl = value;
					this.SendPropertyChanged("Postop6Lkl");
					this.OnPostop6LklChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop6Krtn", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> Postop6Krtn
		{
			get
			{
				return this._Postop6Krtn;
			}
			set
			{
				if ((this._Postop6Krtn != value))
				{
					this.OnPostop6KrtnChanging(value);
					this.SendPropertyChanging();
					this._Postop6Krtn = value;
					this.SendPropertyChanged("Postop6Krtn");
					this.OnPostop6KrtnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop12Lkl", DbType="NVarChar(5)")]
		public string Postop12Lkl
		{
			get
			{
				return this._Postop12Lkl;
			}
			set
			{
				if ((this._Postop12Lkl != value))
				{
					this.OnPostop12LklChanging(value);
					this.SendPropertyChanging();
					this._Postop12Lkl = value;
					this.SendPropertyChanged("Postop12Lkl");
					this.OnPostop12LklChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop12Krtn", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> Postop12Krtn
		{
			get
			{
				return this._Postop12Krtn;
			}
			set
			{
				if ((this._Postop12Krtn != value))
				{
					this.OnPostop12KrtnChanging(value);
					this.SendPropertyChanging();
					this._Postop12Krtn = value;
					this.SendPropertyChanged("Postop12Krtn");
					this.OnPostop12KrtnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblHasta_TblTakip", Storage="_TblHasta", ThisKey="HastaId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public TblHasta TblHasta
		{
			get
			{
				return this._TblHasta.Entity;
			}
			set
			{
				TblHasta previousValue = this._TblHasta.Entity;
				if (((previousValue != value) 
							|| (this._TblHasta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblHasta.Entity = null;
						previousValue.TblTakips.Remove(this);
					}
					this._TblHasta.Entity = value;
					if ((value != null))
					{
						value.TblTakips.Add(this);
						this._HastaId = value.Id;
					}
					else
					{
						this._HastaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("TblHasta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbkPeropErKomp")]
	public partial class TbkPeropErKomp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _PeropErkenKomp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPeropErkenKompChanging(string value);
    partial void OnPeropErkenKompChanged();
    #endregion
		
		public TbkPeropErKomp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeropErkenKomp", DbType="NVarChar(100)")]
		public string PeropErkenKomp
		{
			get
			{
				return this._PeropErkenKomp;
			}
			set
			{
				if ((this._PeropErkenKomp != value))
				{
					this.OnPeropErkenKompChanging(value);
					this.SendPropertyChanging();
					this._PeropErkenKomp = value;
					this.SendPropertyChanged("PeropErkenKomp");
					this.OnPeropErkenKompChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_PatalojikVeri")]
	public partial class Tbl_PatalojikVeri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _HastaId;
		
		private string _Patoloji;
		
		private string _AltGr;
		
		private string _FurhmanGrade;
		
		private string _PatolojikEvre;
		
		private string _CerrahiSinir;
		
		private EntityRef<TblHasta> _TblHasta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHastaIdChanging(System.Nullable<int> value);
    partial void OnHastaIdChanged();
    partial void OnPatolojiChanging(string value);
    partial void OnPatolojiChanged();
    partial void OnAltGrChanging(string value);
    partial void OnAltGrChanged();
    partial void OnFurhmanGradeChanging(string value);
    partial void OnFurhmanGradeChanged();
    partial void OnPatolojikEvreChanging(string value);
    partial void OnPatolojikEvreChanged();
    partial void OnCerrahiSinirChanging(string value);
    partial void OnCerrahiSinirChanged();
    #endregion
		
		public Tbl_PatalojikVeri()
		{
			this._TblHasta = default(EntityRef<TblHasta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaId", DbType="Int")]
		public System.Nullable<int> HastaId
		{
			get
			{
				return this._HastaId;
			}
			set
			{
				if ((this._HastaId != value))
				{
					if (this._TblHasta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIdChanging(value);
					this.SendPropertyChanging();
					this._HastaId = value;
					this.SendPropertyChanged("HastaId");
					this.OnHastaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patoloji", DbType="NVarChar(50)")]
		public string Patoloji
		{
			get
			{
				return this._Patoloji;
			}
			set
			{
				if ((this._Patoloji != value))
				{
					this.OnPatolojiChanging(value);
					this.SendPropertyChanging();
					this._Patoloji = value;
					this.SendPropertyChanged("Patoloji");
					this.OnPatolojiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltGr", DbType="NVarChar(100)")]
		public string AltGr
		{
			get
			{
				return this._AltGr;
			}
			set
			{
				if ((this._AltGr != value))
				{
					this.OnAltGrChanging(value);
					this.SendPropertyChanging();
					this._AltGr = value;
					this.SendPropertyChanged("AltGr");
					this.OnAltGrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FurhmanGrade", DbType="NVarChar(20)")]
		public string FurhmanGrade
		{
			get
			{
				return this._FurhmanGrade;
			}
			set
			{
				if ((this._FurhmanGrade != value))
				{
					this.OnFurhmanGradeChanging(value);
					this.SendPropertyChanging();
					this._FurhmanGrade = value;
					this.SendPropertyChanged("FurhmanGrade");
					this.OnFurhmanGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatolojikEvre", DbType="NVarChar(10)")]
		public string PatolojikEvre
		{
			get
			{
				return this._PatolojikEvre;
			}
			set
			{
				if ((this._PatolojikEvre != value))
				{
					this.OnPatolojikEvreChanging(value);
					this.SendPropertyChanging();
					this._PatolojikEvre = value;
					this.SendPropertyChanged("PatolojikEvre");
					this.OnPatolojikEvreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CerrahiSinir", DbType="NVarChar(10)")]
		public string CerrahiSinir
		{
			get
			{
				return this._CerrahiSinir;
			}
			set
			{
				if ((this._CerrahiSinir != value))
				{
					this.OnCerrahiSinirChanging(value);
					this.SendPropertyChanging();
					this._CerrahiSinir = value;
					this.SendPropertyChanged("CerrahiSinir");
					this.OnCerrahiSinirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblHasta_Tbl_PatalojikVeri", Storage="_TblHasta", ThisKey="HastaId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public TblHasta TblHasta
		{
			get
			{
				return this._TblHasta.Entity;
			}
			set
			{
				TblHasta previousValue = this._TblHasta.Entity;
				if (((previousValue != value) 
							|| (this._TblHasta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblHasta.Entity = null;
						previousValue.Tbl_PatalojikVeris.Remove(this);
					}
					this._TblHasta.Entity = value;
					if ((value != null))
					{
						value.Tbl_PatalojikVeris.Add(this);
						this._HastaId = value.Id;
					}
					else
					{
						this._HastaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("TblHasta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblAltGrup")]
	public partial class TblAltGrup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _AltGrup;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAltGrupChanging(string value);
    partial void OnAltGrupChanged();
    #endregion
		
		public TblAltGrup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltGrup", DbType="NVarChar(100)")]
		public string AltGrup
		{
			get
			{
				return this._AltGrup;
			}
			set
			{
				if ((this._AltGrup != value))
				{
					this.OnAltGrupChanging(value);
					this.SendPropertyChanging();
					this._AltGrup = value;
					this.SendPropertyChanged("AltGrup");
					this.OnAltGrupChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblDemograf")]
	public partial class TblDemograf : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _HastaId;
		
		private System.Nullable<int> _Boy;
		
		private System.Nullable<int> _Yas;
		
		private System.Nullable<decimal> _Kilo;
		
		private System.Nullable<int> _BMI;
		
		private System.Nullable<int> _ASA;
		
		private string _Dr;
		
		private string _Cins;
		
		private string _Taraf;
		
		private string _Lklzsyn;
		
		private System.Nullable<int> _Boyut;
		
		private string _Komorbid;
		
		private EntityRef<TblHasta> _TblHasta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHastaIdChanging(System.Nullable<int> value);
    partial void OnHastaIdChanged();
    partial void OnBoyChanging(System.Nullable<int> value);
    partial void OnBoyChanged();
    partial void OnYasChanging(System.Nullable<int> value);
    partial void OnYasChanged();
    partial void OnKiloChanging(System.Nullable<decimal> value);
    partial void OnKiloChanged();
    partial void OnBMIChanging(System.Nullable<int> value);
    partial void OnBMIChanged();
    partial void OnASAChanging(System.Nullable<int> value);
    partial void OnASAChanged();
    partial void OnDrChanging(string value);
    partial void OnDrChanged();
    partial void OnCinsChanging(string value);
    partial void OnCinsChanged();
    partial void OnTarafChanging(string value);
    partial void OnTarafChanged();
    partial void OnLklzsynChanging(string value);
    partial void OnLklzsynChanged();
    partial void OnBoyutChanging(System.Nullable<int> value);
    partial void OnBoyutChanged();
    partial void OnKomorbidChanging(string value);
    partial void OnKomorbidChanged();
    #endregion
		
		public TblDemograf()
		{
			this._TblHasta = default(EntityRef<TblHasta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaId", DbType="Int")]
		public System.Nullable<int> HastaId
		{
			get
			{
				return this._HastaId;
			}
			set
			{
				if ((this._HastaId != value))
				{
					if (this._TblHasta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIdChanging(value);
					this.SendPropertyChanging();
					this._HastaId = value;
					this.SendPropertyChanged("HastaId");
					this.OnHastaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boy", DbType="Int")]
		public System.Nullable<int> Boy
		{
			get
			{
				return this._Boy;
			}
			set
			{
				if ((this._Boy != value))
				{
					this.OnBoyChanging(value);
					this.SendPropertyChanging();
					this._Boy = value;
					this.SendPropertyChanged("Boy");
					this.OnBoyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yas", DbType="Int")]
		public System.Nullable<int> Yas
		{
			get
			{
				return this._Yas;
			}
			set
			{
				if ((this._Yas != value))
				{
					this.OnYasChanging(value);
					this.SendPropertyChanging();
					this._Yas = value;
					this.SendPropertyChanged("Yas");
					this.OnYasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kilo", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> Kilo
		{
			get
			{
				return this._Kilo;
			}
			set
			{
				if ((this._Kilo != value))
				{
					this.OnKiloChanging(value);
					this.SendPropertyChanging();
					this._Kilo = value;
					this.SendPropertyChanged("Kilo");
					this.OnKiloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Int")]
		public System.Nullable<int> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this.OnBMIChanging(value);
					this.SendPropertyChanging();
					this._BMI = value;
					this.SendPropertyChanged("BMI");
					this.OnBMIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASA", DbType="Int")]
		public System.Nullable<int> ASA
		{
			get
			{
				return this._ASA;
			}
			set
			{
				if ((this._ASA != value))
				{
					this.OnASAChanging(value);
					this.SendPropertyChanging();
					this._ASA = value;
					this.SendPropertyChanged("ASA");
					this.OnASAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dr", DbType="NVarChar(100)")]
		public string Dr
		{
			get
			{
				return this._Dr;
			}
			set
			{
				if ((this._Dr != value))
				{
					this.OnDrChanging(value);
					this.SendPropertyChanging();
					this._Dr = value;
					this.SendPropertyChanged("Dr");
					this.OnDrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cins", DbType="NVarChar(5)")]
		public string Cins
		{
			get
			{
				return this._Cins;
			}
			set
			{
				if ((this._Cins != value))
				{
					this.OnCinsChanging(value);
					this.SendPropertyChanging();
					this._Cins = value;
					this.SendPropertyChanged("Cins");
					this.OnCinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taraf", DbType="NVarChar(5)")]
		public string Taraf
		{
			get
			{
				return this._Taraf;
			}
			set
			{
				if ((this._Taraf != value))
				{
					this.OnTarafChanging(value);
					this.SendPropertyChanging();
					this._Taraf = value;
					this.SendPropertyChanged("Taraf");
					this.OnTarafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lklzsyn", DbType="NVarChar(100)")]
		public string Lklzsyn
		{
			get
			{
				return this._Lklzsyn;
			}
			set
			{
				if ((this._Lklzsyn != value))
				{
					this.OnLklzsynChanging(value);
					this.SendPropertyChanging();
					this._Lklzsyn = value;
					this.SendPropertyChanged("Lklzsyn");
					this.OnLklzsynChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boyut", DbType="Int")]
		public System.Nullable<int> Boyut
		{
			get
			{
				return this._Boyut;
			}
			set
			{
				if ((this._Boyut != value))
				{
					this.OnBoyutChanging(value);
					this.SendPropertyChanging();
					this._Boyut = value;
					this.SendPropertyChanged("Boyut");
					this.OnBoyutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Komorbid", DbType="NVarChar(50)")]
		public string Komorbid
		{
			get
			{
				return this._Komorbid;
			}
			set
			{
				if ((this._Komorbid != value))
				{
					this.OnKomorbidChanging(value);
					this.SendPropertyChanging();
					this._Komorbid = value;
					this.SendPropertyChanged("Komorbid");
					this.OnKomorbidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblHasta_TblDemograf", Storage="_TblHasta", ThisKey="HastaId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public TblHasta TblHasta
		{
			get
			{
				return this._TblHasta.Entity;
			}
			set
			{
				TblHasta previousValue = this._TblHasta.Entity;
				if (((previousValue != value) 
							|| (this._TblHasta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblHasta.Entity = null;
						previousValue.TblDemografs.Remove(this);
					}
					this._TblHasta.Entity = value;
					if ((value != null))
					{
						value.TblDemografs.Add(this);
						this._HastaId = value.Id;
					}
					else
					{
						this._HastaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("TblHasta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblDoktor")]
	public partial class TblDoktor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _DoktorAdi;
		
		private string _DoktorSoyad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDoktorAdiChanging(string value);
    partial void OnDoktorAdiChanged();
    partial void OnDoktorSoyadChanging(string value);
    partial void OnDoktorSoyadChanged();
    #endregion
		
		public TblDoktor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorAdi", DbType="NVarChar(100)")]
		public string DoktorAdi
		{
			get
			{
				return this._DoktorAdi;
			}
			set
			{
				if ((this._DoktorAdi != value))
				{
					this.OnDoktorAdiChanging(value);
					this.SendPropertyChanging();
					this._DoktorAdi = value;
					this.SendPropertyChanged("DoktorAdi");
					this.OnDoktorAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorSoyad", DbType="NChar(100)")]
		public string DoktorSoyad
		{
			get
			{
				return this._DoktorSoyad;
			}
			set
			{
				if ((this._DoktorSoyad != value))
				{
					this.OnDoktorSoyadChanging(value);
					this.SendPropertyChanging();
					this._DoktorSoyad = value;
					this.SendPropertyChanged("DoktorSoyad");
					this.OnDoktorSoyadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblFuhrmanGrade")]
	public partial class TblFuhrmanGrade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FuhrmanGrade;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFuhrmanGradeChanging(string value);
    partial void OnFuhrmanGradeChanged();
    #endregion
		
		public TblFuhrmanGrade()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FuhrmanGrade", DbType="NVarChar(100)")]
		public string FuhrmanGrade
		{
			get
			{
				return this._FuhrmanGrade;
			}
			set
			{
				if ((this._FuhrmanGrade != value))
				{
					this.OnFuhrmanGradeChanging(value);
					this.SendPropertyChanging();
					this._FuhrmanGrade = value;
					this.SendPropertyChanged("FuhrmanGrade");
					this.OnFuhrmanGradeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblHasta")]
	public partial class TblHasta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _Prot;
		
		private System.Nullable<System.DateTime> _Opttar;
		
		private string _Opttur;
		
		private System.Nullable<int> _Takip;
		
		private System.Nullable<int> _Anah;
		
		private EntitySet<TblTakip> _TblTakips;
		
		private EntitySet<Tbl_PatalojikVeri> _Tbl_PatalojikVeris;
		
		private EntitySet<TblDemograf> _TblDemografs;
		
		private EntitySet<TblOperaf> _TblOperafs;
		
		private EntitySet<TblPosOperaf> _TblPosOperafs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnProtChanging(string value);
    partial void OnProtChanged();
    partial void OnOpttarChanging(System.Nullable<System.DateTime> value);
    partial void OnOpttarChanged();
    partial void OnOptturChanging(string value);
    partial void OnOptturChanged();
    partial void OnTakipChanging(System.Nullable<int> value);
    partial void OnTakipChanged();
    partial void OnAnahChanging(System.Nullable<int> value);
    partial void OnAnahChanged();
    #endregion
		
		public TblHasta()
		{
			this._TblTakips = new EntitySet<TblTakip>(new Action<TblTakip>(this.attach_TblTakips), new Action<TblTakip>(this.detach_TblTakips));
			this._Tbl_PatalojikVeris = new EntitySet<Tbl_PatalojikVeri>(new Action<Tbl_PatalojikVeri>(this.attach_Tbl_PatalojikVeris), new Action<Tbl_PatalojikVeri>(this.detach_Tbl_PatalojikVeris));
			this._TblDemografs = new EntitySet<TblDemograf>(new Action<TblDemograf>(this.attach_TblDemografs), new Action<TblDemograf>(this.detach_TblDemografs));
			this._TblOperafs = new EntitySet<TblOperaf>(new Action<TblOperaf>(this.attach_TblOperafs), new Action<TblOperaf>(this.detach_TblOperafs));
			this._TblPosOperafs = new EntitySet<TblPosOperaf>(new Action<TblPosOperaf>(this.attach_TblPosOperafs), new Action<TblPosOperaf>(this.detach_TblPosOperafs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(50)")]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prot", DbType="NVarChar(50)")]
		public string Prot
		{
			get
			{
				return this._Prot;
			}
			set
			{
				if ((this._Prot != value))
				{
					this.OnProtChanging(value);
					this.SendPropertyChanging();
					this._Prot = value;
					this.SendPropertyChanged("Prot");
					this.OnProtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opttar", DbType="Date")]
		public System.Nullable<System.DateTime> Opttar
		{
			get
			{
				return this._Opttar;
			}
			set
			{
				if ((this._Opttar != value))
				{
					this.OnOpttarChanging(value);
					this.SendPropertyChanging();
					this._Opttar = value;
					this.SendPropertyChanged("Opttar");
					this.OnOpttarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opttur", DbType="NVarChar(100)")]
		public string Opttur
		{
			get
			{
				return this._Opttur;
			}
			set
			{
				if ((this._Opttur != value))
				{
					this.OnOptturChanging(value);
					this.SendPropertyChanging();
					this._Opttur = value;
					this.SendPropertyChanged("Opttur");
					this.OnOptturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="Int")]
		public System.Nullable<int> Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this.OnTakipChanging(value);
					this.SendPropertyChanging();
					this._Takip = value;
					this.SendPropertyChanged("Takip");
					this.OnTakipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anah", DbType="Int")]
		public System.Nullable<int> Anah
		{
			get
			{
				return this._Anah;
			}
			set
			{
				if ((this._Anah != value))
				{
					this.OnAnahChanging(value);
					this.SendPropertyChanging();
					this._Anah = value;
					this.SendPropertyChanged("Anah");
					this.OnAnahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblHasta_TblTakip", Storage="_TblTakips", ThisKey="Id", OtherKey="HastaId")]
		public EntitySet<TblTakip> TblTakips
		{
			get
			{
				return this._TblTakips;
			}
			set
			{
				this._TblTakips.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblHasta_Tbl_PatalojikVeri", Storage="_Tbl_PatalojikVeris", ThisKey="Id", OtherKey="HastaId")]
		public EntitySet<Tbl_PatalojikVeri> Tbl_PatalojikVeris
		{
			get
			{
				return this._Tbl_PatalojikVeris;
			}
			set
			{
				this._Tbl_PatalojikVeris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblHasta_TblDemograf", Storage="_TblDemografs", ThisKey="Id", OtherKey="HastaId")]
		public EntitySet<TblDemograf> TblDemografs
		{
			get
			{
				return this._TblDemografs;
			}
			set
			{
				this._TblDemografs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblHasta_TblOperaf", Storage="_TblOperafs", ThisKey="Id", OtherKey="HastaId")]
		public EntitySet<TblOperaf> TblOperafs
		{
			get
			{
				return this._TblOperafs;
			}
			set
			{
				this._TblOperafs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblHasta_TblPosOperaf", Storage="_TblPosOperafs", ThisKey="Id", OtherKey="HastaId")]
		public EntitySet<TblPosOperaf> TblPosOperafs
		{
			get
			{
				return this._TblPosOperafs;
			}
			set
			{
				this._TblPosOperafs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TblTakips(TblTakip entity)
		{
			this.SendPropertyChanging();
			entity.TblHasta = this;
		}
		
		private void detach_TblTakips(TblTakip entity)
		{
			this.SendPropertyChanging();
			entity.TblHasta = null;
		}
		
		private void attach_Tbl_PatalojikVeris(Tbl_PatalojikVeri entity)
		{
			this.SendPropertyChanging();
			entity.TblHasta = this;
		}
		
		private void detach_Tbl_PatalojikVeris(Tbl_PatalojikVeri entity)
		{
			this.SendPropertyChanging();
			entity.TblHasta = null;
		}
		
		private void attach_TblDemografs(TblDemograf entity)
		{
			this.SendPropertyChanging();
			entity.TblHasta = this;
		}
		
		private void detach_TblDemografs(TblDemograf entity)
		{
			this.SendPropertyChanging();
			entity.TblHasta = null;
		}
		
		private void attach_TblOperafs(TblOperaf entity)
		{
			this.SendPropertyChanging();
			entity.TblHasta = this;
		}
		
		private void detach_TblOperafs(TblOperaf entity)
		{
			this.SendPropertyChanging();
			entity.TblHasta = null;
		}
		
		private void attach_TblPosOperafs(TblPosOperaf entity)
		{
			this.SendPropertyChanging();
			entity.TblHasta = this;
		}
		
		private void detach_TblPosOperafs(TblPosOperaf entity)
		{
			this.SendPropertyChanging();
			entity.TblHasta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblKomorbidite")]
	public partial class TblKomorbidite : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KomorbiditeAdı;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKomorbiditeAdıChanging(string value);
    partial void OnKomorbiditeAdıChanged();
    #endregion
		
		public TblKomorbidite()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KomorbiditeAdı", DbType="NVarChar(100)")]
		public string KomorbiditeAdı
		{
			get
			{
				return this._KomorbiditeAdı;
			}
			set
			{
				if ((this._KomorbiditeAdı != value))
				{
					this.OnKomorbiditeAdıChanging(value);
					this.SendPropertyChanging();
					this._KomorbiditeAdı = value;
					this.SendPropertyChanged("KomorbiditeAdı");
					this.OnKomorbiditeAdıChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblKompClavien")]
	public partial class TblKompClavien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KompClavien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKompClavienChanging(string value);
    partial void OnKompClavienChanged();
    #endregion
		
		public TblKompClavien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KompClavien", DbType="NVarChar(50)")]
		public string KompClavien
		{
			get
			{
				return this._KompClavien;
			}
			set
			{
				if ((this._KompClavien != value))
				{
					this.OnKompClavienChanging(value);
					this.SendPropertyChanging();
					this._KompClavien = value;
					this.SendPropertyChanged("KompClavien");
					this.OnKompClavienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLokalizasyon")]
	public partial class tblLokalizasyon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Lokalizayson;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLokalizaysonChanging(string value);
    partial void OnLokalizaysonChanged();
    #endregion
		
		public tblLokalizasyon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lokalizayson", DbType="NVarChar(100)")]
		public string Lokalizayson
		{
			get
			{
				return this._Lokalizayson;
			}
			set
			{
				if ((this._Lokalizayson != value))
				{
					this.OnLokalizaysonChanging(value);
					this.SendPropertyChanging();
					this._Lokalizayson = value;
					this.SendPropertyChanged("Lokalizayson");
					this.OnLokalizaysonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblOperaf")]
	public partial class TblOperaf : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _HastaId;
		
		private string _PksAc;
		
		private string _SIK;
		
		private string _Coop;
		
		private System.Nullable<int> _Iskemi;
		
		private System.Nullable<int> _Portsay;
		
		private string _Yrdmynt;
		
		private System.Nullable<int> _Sure;
		
		private System.Nullable<int> _Dren;
		
		private System.Nullable<int> _Kanama;
		
		private System.Nullable<int> _Piyes;
		
		private EntityRef<TblHasta> _TblHasta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHastaIdChanging(System.Nullable<int> value);
    partial void OnHastaIdChanged();
    partial void OnPksAcChanging(string value);
    partial void OnPksAcChanged();
    partial void OnSIKChanging(string value);
    partial void OnSIKChanged();
    partial void OnCoopChanging(string value);
    partial void OnCoopChanged();
    partial void OnIskemiChanging(System.Nullable<int> value);
    partial void OnIskemiChanged();
    partial void OnPortsayChanging(System.Nullable<int> value);
    partial void OnPortsayChanged();
    partial void OnYrdmyntChanging(string value);
    partial void OnYrdmyntChanged();
    partial void OnSureChanging(System.Nullable<int> value);
    partial void OnSureChanged();
    partial void OnDrenChanging(System.Nullable<int> value);
    partial void OnDrenChanged();
    partial void OnKanamaChanging(System.Nullable<int> value);
    partial void OnKanamaChanged();
    partial void OnPiyesChanging(System.Nullable<int> value);
    partial void OnPiyesChanged();
    #endregion
		
		public TblOperaf()
		{
			this._TblHasta = default(EntityRef<TblHasta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaId", DbType="Int")]
		public System.Nullable<int> HastaId
		{
			get
			{
				return this._HastaId;
			}
			set
			{
				if ((this._HastaId != value))
				{
					if (this._TblHasta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIdChanging(value);
					this.SendPropertyChanging();
					this._HastaId = value;
					this.SendPropertyChanged("HastaId");
					this.OnHastaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PksAc", DbType="NVarChar(5)")]
		public string PksAc
		{
			get
			{
				return this._PksAc;
			}
			set
			{
				if ((this._PksAc != value))
				{
					this.OnPksAcChanging(value);
					this.SendPropertyChanging();
					this._PksAc = value;
					this.SendPropertyChanged("PksAc");
					this.OnPksAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIK", DbType="NVarChar(15)")]
		public string SIK
		{
			get
			{
				return this._SIK;
			}
			set
			{
				if ((this._SIK != value))
				{
					this.OnSIKChanging(value);
					this.SendPropertyChanging();
					this._SIK = value;
					this.SendPropertyChanged("SIK");
					this.OnSIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coop", DbType="NVarChar(100)")]
		public string Coop
		{
			get
			{
				return this._Coop;
			}
			set
			{
				if ((this._Coop != value))
				{
					this.OnCoopChanging(value);
					this.SendPropertyChanging();
					this._Coop = value;
					this.SendPropertyChanged("Coop");
					this.OnCoopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iskemi", DbType="Int")]
		public System.Nullable<int> Iskemi
		{
			get
			{
				return this._Iskemi;
			}
			set
			{
				if ((this._Iskemi != value))
				{
					this.OnIskemiChanging(value);
					this.SendPropertyChanging();
					this._Iskemi = value;
					this.SendPropertyChanged("Iskemi");
					this.OnIskemiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Portsay", DbType="Int")]
		public System.Nullable<int> Portsay
		{
			get
			{
				return this._Portsay;
			}
			set
			{
				if ((this._Portsay != value))
				{
					this.OnPortsayChanging(value);
					this.SendPropertyChanging();
					this._Portsay = value;
					this.SendPropertyChanged("Portsay");
					this.OnPortsayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yrdmynt", DbType="NVarChar(100)")]
		public string Yrdmynt
		{
			get
			{
				return this._Yrdmynt;
			}
			set
			{
				if ((this._Yrdmynt != value))
				{
					this.OnYrdmyntChanging(value);
					this.SendPropertyChanging();
					this._Yrdmynt = value;
					this.SendPropertyChanged("Yrdmynt");
					this.OnYrdmyntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Int")]
		public System.Nullable<int> Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this.OnSureChanging(value);
					this.SendPropertyChanging();
					this._Sure = value;
					this.SendPropertyChanged("Sure");
					this.OnSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dren", DbType="Int")]
		public System.Nullable<int> Dren
		{
			get
			{
				return this._Dren;
			}
			set
			{
				if ((this._Dren != value))
				{
					this.OnDrenChanging(value);
					this.SendPropertyChanging();
					this._Dren = value;
					this.SendPropertyChanged("Dren");
					this.OnDrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kanama", DbType="Int")]
		public System.Nullable<int> Kanama
		{
			get
			{
				return this._Kanama;
			}
			set
			{
				if ((this._Kanama != value))
				{
					this.OnKanamaChanging(value);
					this.SendPropertyChanging();
					this._Kanama = value;
					this.SendPropertyChanged("Kanama");
					this.OnKanamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piyes", DbType="Int")]
		public System.Nullable<int> Piyes
		{
			get
			{
				return this._Piyes;
			}
			set
			{
				if ((this._Piyes != value))
				{
					this.OnPiyesChanging(value);
					this.SendPropertyChanging();
					this._Piyes = value;
					this.SendPropertyChanged("Piyes");
					this.OnPiyesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblHasta_TblOperaf", Storage="_TblHasta", ThisKey="HastaId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public TblHasta TblHasta
		{
			get
			{
				return this._TblHasta.Entity;
			}
			set
			{
				TblHasta previousValue = this._TblHasta.Entity;
				if (((previousValue != value) 
							|| (this._TblHasta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblHasta.Entity = null;
						previousValue.TblOperafs.Remove(this);
					}
					this._TblHasta.Entity = value;
					if ((value != null))
					{
						value.TblOperafs.Add(this);
						this._HastaId = value.Id;
					}
					else
					{
						this._HastaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("TblHasta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblOpTuru")]
	public partial class TblOpTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _OpTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnOpTuruChanging(string value);
    partial void OnOpTuruChanged();
    #endregion
		
		public TblOpTuru()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTuru", DbType="NVarChar(100)")]
		public string OpTuru
		{
			get
			{
				return this._OpTuru;
			}
			set
			{
				if ((this._OpTuru != value))
				{
					this.OnOpTuruChanging(value);
					this.SendPropertyChanging();
					this._OpTuru = value;
					this.SendPropertyChanged("OpTuru");
					this.OnOpTuruChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblPatEvre")]
	public partial class TblPatEvre : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _PatEvre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPatEvreChanging(string value);
    partial void OnPatEvreChanged();
    #endregion
		
		public TblPatEvre()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatEvre", DbType="NVarChar(50)")]
		public string PatEvre
		{
			get
			{
				return this._PatEvre;
			}
			set
			{
				if ((this._PatEvre != value))
				{
					this.OnPatEvreChanging(value);
					this.SendPropertyChanging();
					this._PatEvre = value;
					this.SendPropertyChanged("PatEvre");
					this.OnPatEvreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblPatoloji")]
	public partial class TblPatoloji : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Patoloji;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPatolojiChanging(string value);
    partial void OnPatolojiChanged();
    #endregion
		
		public TblPatoloji()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patoloji", DbType="NChar(100)")]
		public string Patoloji
		{
			get
			{
				return this._Patoloji;
			}
			set
			{
				if ((this._Patoloji != value))
				{
					this.OnPatolojiChanging(value);
					this.SendPropertyChanging();
					this._Patoloji = value;
					this.SendPropertyChanged("Patoloji");
					this.OnPatolojiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblPosOperaf")]
	public partial class TblPosOperaf : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _PeropErkenKomp;
		
		private string _PostopAn;
		
		private string _Sonda;
		
		private System.Nullable<int> _HospSur;
		
		private System.Nullable<decimal> _preopKeratin;
		
		private System.Nullable<decimal> _PostopKreatin;
		
		private System.Nullable<decimal> _PreopHtc;
		
		private System.Nullable<decimal> _PostopHct;
		
		private System.Nullable<decimal> _PreobHb;
		
		private System.Nullable<decimal> _PostopHb;
		
		private string _Takip;
		
		private string _Tel;
		
		private string _PostopGecKomp;
		
		private string _KompClavien;
		
		private System.Nullable<int> _HastaId;
		
		private EntityRef<TblHasta> _TblHasta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPeropErkenKompChanging(string value);
    partial void OnPeropErkenKompChanged();
    partial void OnPostopAnChanging(string value);
    partial void OnPostopAnChanged();
    partial void OnSondaChanging(string value);
    partial void OnSondaChanged();
    partial void OnHospSurChanging(System.Nullable<int> value);
    partial void OnHospSurChanged();
    partial void OnpreopKeratinChanging(System.Nullable<decimal> value);
    partial void OnpreopKeratinChanged();
    partial void OnPostopKreatinChanging(System.Nullable<decimal> value);
    partial void OnPostopKreatinChanged();
    partial void OnPreopHtcChanging(System.Nullable<decimal> value);
    partial void OnPreopHtcChanged();
    partial void OnPostopHctChanging(System.Nullable<decimal> value);
    partial void OnPostopHctChanged();
    partial void OnPreobHbChanging(System.Nullable<decimal> value);
    partial void OnPreobHbChanged();
    partial void OnPostopHbChanging(System.Nullable<decimal> value);
    partial void OnPostopHbChanged();
    partial void OnTakipChanging(string value);
    partial void OnTakipChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnPostopGecKompChanging(string value);
    partial void OnPostopGecKompChanged();
    partial void OnKompClavienChanging(string value);
    partial void OnKompClavienChanged();
    partial void OnHastaIdChanging(System.Nullable<int> value);
    partial void OnHastaIdChanged();
    #endregion
		
		public TblPosOperaf()
		{
			this._TblHasta = default(EntityRef<TblHasta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeropErkenKomp", DbType="NVarChar(100)")]
		public string PeropErkenKomp
		{
			get
			{
				return this._PeropErkenKomp;
			}
			set
			{
				if ((this._PeropErkenKomp != value))
				{
					this.OnPeropErkenKompChanging(value);
					this.SendPropertyChanging();
					this._PeropErkenKomp = value;
					this.SendPropertyChanged("PeropErkenKomp");
					this.OnPeropErkenKompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopAn", DbType="NVarChar(50)")]
		public string PostopAn
		{
			get
			{
				return this._PostopAn;
			}
			set
			{
				if ((this._PostopAn != value))
				{
					this.OnPostopAnChanging(value);
					this.SendPropertyChanging();
					this._PostopAn = value;
					this.SendPropertyChanged("PostopAn");
					this.OnPostopAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sonda", DbType="NVarChar(8)")]
		public string Sonda
		{
			get
			{
				return this._Sonda;
			}
			set
			{
				if ((this._Sonda != value))
				{
					this.OnSondaChanging(value);
					this.SendPropertyChanging();
					this._Sonda = value;
					this.SendPropertyChanged("Sonda");
					this.OnSondaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HospSur", DbType="Int")]
		public System.Nullable<int> HospSur
		{
			get
			{
				return this._HospSur;
			}
			set
			{
				if ((this._HospSur != value))
				{
					this.OnHospSurChanging(value);
					this.SendPropertyChanging();
					this._HospSur = value;
					this.SendPropertyChanged("HospSur");
					this.OnHospSurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preopKeratin", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> preopKeratin
		{
			get
			{
				return this._preopKeratin;
			}
			set
			{
				if ((this._preopKeratin != value))
				{
					this.OnpreopKeratinChanging(value);
					this.SendPropertyChanging();
					this._preopKeratin = value;
					this.SendPropertyChanged("preopKeratin");
					this.OnpreopKeratinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopKreatin", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> PostopKreatin
		{
			get
			{
				return this._PostopKreatin;
			}
			set
			{
				if ((this._PostopKreatin != value))
				{
					this.OnPostopKreatinChanging(value);
					this.SendPropertyChanging();
					this._PostopKreatin = value;
					this.SendPropertyChanged("PostopKreatin");
					this.OnPostopKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreopHtc", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PreopHtc
		{
			get
			{
				return this._PreopHtc;
			}
			set
			{
				if ((this._PreopHtc != value))
				{
					this.OnPreopHtcChanging(value);
					this.SendPropertyChanging();
					this._PreopHtc = value;
					this.SendPropertyChanged("PreopHtc");
					this.OnPreopHtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopHct", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostopHct
		{
			get
			{
				return this._PostopHct;
			}
			set
			{
				if ((this._PostopHct != value))
				{
					this.OnPostopHctChanging(value);
					this.SendPropertyChanging();
					this._PostopHct = value;
					this.SendPropertyChanged("PostopHct");
					this.OnPostopHctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreobHb", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PreobHb
		{
			get
			{
				return this._PreobHb;
			}
			set
			{
				if ((this._PreobHb != value))
				{
					this.OnPreobHbChanging(value);
					this.SendPropertyChanging();
					this._PreobHb = value;
					this.SendPropertyChanged("PreobHb");
					this.OnPreobHbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopHb", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostopHb
		{
			get
			{
				return this._PostopHb;
			}
			set
			{
				if ((this._PostopHb != value))
				{
					this.OnPostopHbChanging(value);
					this.SendPropertyChanging();
					this._PostopHb = value;
					this.SendPropertyChanged("PostopHb");
					this.OnPostopHbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="NVarChar(100)")]
		public string Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this.OnTakipChanging(value);
					this.SendPropertyChanging();
					this._Takip = value;
					this.SendPropertyChanged("Takip");
					this.OnTakipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(100)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopGecKomp", DbType="NVarChar(100)")]
		public string PostopGecKomp
		{
			get
			{
				return this._PostopGecKomp;
			}
			set
			{
				if ((this._PostopGecKomp != value))
				{
					this.OnPostopGecKompChanging(value);
					this.SendPropertyChanging();
					this._PostopGecKomp = value;
					this.SendPropertyChanged("PostopGecKomp");
					this.OnPostopGecKompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KompClavien", DbType="NVarChar(10)")]
		public string KompClavien
		{
			get
			{
				return this._KompClavien;
			}
			set
			{
				if ((this._KompClavien != value))
				{
					this.OnKompClavienChanging(value);
					this.SendPropertyChanging();
					this._KompClavien = value;
					this.SendPropertyChanged("KompClavien");
					this.OnKompClavienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaId", DbType="Int")]
		public System.Nullable<int> HastaId
		{
			get
			{
				return this._HastaId;
			}
			set
			{
				if ((this._HastaId != value))
				{
					if (this._TblHasta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIdChanging(value);
					this.SendPropertyChanging();
					this._HastaId = value;
					this.SendPropertyChanged("HastaId");
					this.OnHastaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblHasta_TblPosOperaf", Storage="_TblHasta", ThisKey="HastaId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public TblHasta TblHasta
		{
			get
			{
				return this._TblHasta.Entity;
			}
			set
			{
				TblHasta previousValue = this._TblHasta.Entity;
				if (((previousValue != value) 
							|| (this._TblHasta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblHasta.Entity = null;
						previousValue.TblPosOperafs.Remove(this);
					}
					this._TblHasta.Entity = value;
					if ((value != null))
					{
						value.TblPosOperafs.Add(this);
						this._HastaId = value.Id;
					}
					else
					{
						this._HastaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("TblHasta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
